### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by mirh** [ispysoftware/iSpy#12]
- [ ] looking for some way to script zeranoe builds download (nuget?) ([?](https://github.com/UniversalMediaServer/UniversalMediaServer/tree/master/contrib/ffmpeg)). Otherwise checking git LFS. 
- [ ] rebasing the monstrous commits of middle january
- [ ] filtering and whatever cleaning the possibly remaining clutter in git history ([this?](https://github.com/rtyley/bfg-repo-cleaner))
- [ ] linking FFmpeg.AutoGen via submodule
